### ISSUE TITLE
User: Friends/Social

### ISSUE THREAD

**Issue by elizabeth1l** [team-tomatoes/tomato#6]
- [x] user can view all friends #71
- [x] user has option to delete friend #70
- [x] user can see incoming friend requests #69
- [x] user can search for a friend
