### ISSUE TITLE
Accept friend request

### ISSUE THREAD

**Issue by rachelj521** [team-tomatoes/tomato#81]
- [x] requests get removed from pending view when accepted #87
- [x] user's friend list renders newly accepted request #87
- [x] requester has user added to their friend list #108

**Comment by rachelj521** [comment]
- [ ] requests get removed from pending view when accepted
- [ ] user's friend list renders newly accepted request
- [ ] requester has user added to their friend list
